parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    _instanceof:
        App\Core\Presentation\Controller\AbstractController:
            tags: [ 'controller.service_arguments' ]

    Symfony\Component\Serializer\Encoder\JsonEncoder: ~

    App\:
        resource: './../src/'
        exclude:
            - './../src/Application.php'
            - './../src/**/Resources'
            - './../src/**/Domain/Entity'
