parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../../'
        exclude:
            - '../../Application.php'
