# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    php_errors:
        log: true
    serializer:
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'

when@test:
    framework:
        test: true
