version: "3.9"

services:
  redis:
    build:
      context: ./docker
      dockerfile: redis/redis.dockerfile
      args:
        redis_image: ${REDIS_IMAGE}
    env_file: [ .env ]
    networks: [ backend ]
    ports: [ '${REDIS_PORT}:6379' ]
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis:/data:rw

  memcached:
    build:
      context: ./docker
      dockerfile: memcached/memcached.dockerfile
      args:
        memcached_image: ${MEMCACHED_IMAGE}
    env_file: [ .env ]
    networks: [ backend ]
    ports: [ "${MEMCACHED_PORT}:11211" ]
    command: '-m 512'

  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm/php-fpm.dockerfile
      args:
        php_fpm_image: ${PHP_FPM_IMAGE}
        app_dir: ${APP_DIR}
        user: ${USER}
        uid: ${UID}
    depends_on: [ redis, memcached ]
    user: ${USER}:${UID}
    env_file: [ .env ]
    networks: [ backend ]
    dns: [ 8.8.4.4, 8.8.8.8 ]
    extra_hosts: [ "${SERVER_NAME}:host-gateway" ]
    volumes:
      - ./app:${APP_DIR}:rw

  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli/php-cli.dockerfile
      args:
        php_cli_image: ${PHP_CLI_IMAGE}
        app_dir: ${APP_DIR}
        user: ${USER}
        uid: ${UID}
    depends_on: [ php-fpm ]
    env_file: [ .env ]
    networks: [ backend ]
    dns: [ 8.8.4.4, 8.8.8.8 ]
    extra_hosts: [ "${SERVER_NAME}:host-gateway" ]
    volumes:
      - ./app:${APP_DIR}:rw

  nginx:
    build:
      context: ./docker
      dockerfile: nginx/nginx.dockerfile
      args:
        nginx_image: ${NGINX_IMAGE}
        server_name: ${SERVER_NAME}
        app_dir: ${APP_DIR}
        user: ${USER}
        uid: ${UID}
    depends_on: [ php-fpm ]
    env_file: [ .env ]
    networks: [ backend ]
    ports: [ "${NGINX_HTTP_PORT}:80" ]
    volumes:
      - ./app:${APP_DIR}

volumes:
  redis:

networks:
  backend:
