version: "3.9"

x-php-fpm-cfg: &php-fpm-cfg
    build:
        context: ./docker
        dockerfile: dev/php-fpm/php-fpm.dockerfile
        args:
            php_fpm_image: ${PHP_FPM_IMAGE}
            app_dir: ${APP_DIR}
            user: ${USER}
            uid: ${UID}
    environment:
        APP_DIR: ${APP_DIR}
        APP_ENV: ${APP_ENV}
        PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
        SERVER_NAME: ${SERVER_NAME}
        MEMCACHED_HOST: ${MEMCACHED_HOST}
        MEMCACHED_PORT: ${MEMCACHED_PORT}
        XDEBUG_MODE: ${XDEBUG_MODE}
    networks: [ backend ]
    dns: [ 8.8.4.4, 8.8.8.8 ]
    volumes:
        - ./app:${APP_DIR}:rw

x-nginx-cfg: &nginx-cfg
    build:
        context: ./docker
        dockerfile: dev/nginx/nginx.dockerfile
        args:
            nginx_image: ${NGINX_IMAGE}
            server_name: ${SERVER_NAME}
            app_dir: ${APP_DIR}
    environment:
        APP_DIR: ${APP_DIR}
    networks: [ backend ]
    depends_on: [ php-fpm-1, php-fpm-2 ]
    volumes:
        - ./docker/common/nginx/modules-enabled:/etc/nginx/modules-enabled
        - ./app:${APP_DIR}

services:
    nginx-upstream:
        build:
            context: ./docker
            dockerfile: dev/nginx/balancer/nginx.dockerfile
            args:
                nginx_image: ${NGINX_IMAGE}
                server_name: ${SERVER_NAME}
                app_dir: ${APP_DIR}
        environment:
            APP_DIR: ${APP_DIR}
        depends_on: [ nginx-1, nginx-2 ]
        ports: [ "${HTTP_PORT}:80" ]
        networks: [ backend ]
        volumes:
            - ./app/var:${APP_DIR}/var

    nginx-1:
        <<: *nginx-cfg

    php-fpm-1:
        <<: *php-fpm-cfg

    nginx-2:
        <<: *nginx-cfg

    php-fpm-2:
        <<: *php-fpm-cfg

    memcached:
        build:
            context: ./docker
            dockerfile: dev/memcached/memcached.dockerfile
            args:
                memcached_image: ${MEMCACHED_IMAGE}
        networks: [ backend ]
        ports: [ "${MEMCACHED_PORT}:11211" ]
        command: '-m 512'

networks:
    backend:
